image bg apartment exterior = "images/backgrounds/Apartment_Exterior.png"
image bg apartment exterior night = "images/backgrounds/Apartment_Exterior_Night.png"
image bg bathroom = "images/backgrounds/Bathroom.png"
image bg bathroom foggy = "images/backgrounds/Bathroom_Foggy.png"
image bg bedroom day = "images/backgrounds/Bedroom_Day.png"
image bg bedroom evening = "images/backgrounds/Bedroom_Evening.png"
image bg bedroom night = "images/backgrounds/Bedroom_Night.png"
image bg bedroom night dark = "images/backgrounds/Bedroom_Night_Dark.png"
image bg cafeteria day = "images/backgrounds/Cafeteria_Day.png"
image bg city afternoon = "images/backgrounds/City_Afternoon.png"
image bg city morning = "images/backgrounds/City_Morning.png"
image bg city night = "images/backgrounds/City_Night.png"
image bg city raining = "images/backgrounds/City_Raining.png"
image bg classroom day = "images/backgrounds/Classroom_Day.png"
image bg futon room = "images/backgrounds/Futon_Room.png"
image bg futon room night = "images/backgrounds/Futon_Room_Night.png"
image bg kitchen day = "images/backgrounds/Kitchen_Day.png"
image bg kitchen night = "images/backgrounds/Kitchen_Night.png"
image bg laundromat = "images/backgrounds/Laundromat.png"
image bg living room dark = "images/backgrounds/Livingroom_Dark.png"
image bg living room day = "images/backgrounds/Livingroom_Day.png"
image bg living room night = "images/backgrounds/Livingroom_Night.png"
image bg onsen building = "images/backgrounds/Onsen_Building.png"
image bg onsen building night = "images/backgrounds/Onsen_Building_Night.png"
image bg outdoor stairs = "images/backgrounds/Outdoor_Stairs.png"
image bg restaurant a = "images/backgrounds/Restaurant_A.png"
image bg restaurant b = "images/backgrounds/Restaurant_B.png"
image bg school hallway = "images/backgrounds/School_Hallway_Day.png"
image bg sitting room = "images/backgrounds/Sitting_Room.png"
image bg sitting room dark = "images/backgrounds/Sitting_Room_Dark.png"
image bg small apartment kitchen = "images/backgrounds/Small_Apartment_Kitchen.png"
image bg small apartment kitchen night = "images/backgrounds/Small_Apartment_Kitchen_Night.png"
image bg street autumn day = "images/backgrounds/Street_Autumn_Day.png"
image bg street autumn evening = "images/backgrounds/Street_Autumn_Evening.png"
image bg street autumn night = "images/backgrounds/Street_Autumn_Night.png"
image bg street spring day = "images/backgrounds/Street_Spring_Day.png"
image bg street spring evening = "images/backgrounds/Street_Spring_Evening.png"
image bg street spring night = "images/backgrounds/Street_Spring_Night.png"
image bg street spring rain = "images/backgrounds/Street_Spring_Rain.png"
image bg street summer day = "images/backgrounds/Street_Summer_Day.png"
image bg street summer evening = "images/backgrounds/Street_Summer_Evening.png"
image bg street summer night = "images/backgrounds/Street_Summer_Night.png"
image bg street summer rain = "images/backgrounds/Street_Summer_Rain.png"
image bg street summer stars = "images/backgrounds/Street_Summer_Stars.png"
image bg train beach = "images/backgrounds/Train_beach.png"
image bg train day = "images/backgrounds/Train_Day.png"
image bg train day rain = "images/backgrounds/Train_Day_Rain.png"
image bg train evening = "images/backgrounds/Train_Evening.png"
image bg train night = "images/backgrounds/Train_Night.png"
image bg train night rain = "images/backgrounds/Train_Night_Rain.png"
image bg train tunnel = "images/backgrounds/Train_Tunnel.png"
image bg stage = "images/backgrounds/stage.png"
image bg backstage = "images/backgrounds/backstage.png"
image vignette = "images/backgrounds/Vignette.png"
image bg office day:
    "images/backgrounds/office_day.png"
    zoom 2.4
image water:
    "images/backgrounds/water.png"
    zoom 1.6
    ypos 1.2
image bg park:
    "images/backgrounds/park.png"
    zoom 2.4
image bg jail:
    "images/backgrounds/jail.png"
    zoom 2.4
image bg library:
    "images/backgrounds/library_rain.png"
    zoom 2.4
image bg office evening:
    "images/backgrounds/office_evening.png"
    zoom 2.4